export default {
    SET_USER_FIRSTNAME: 'SET_USER_FIRSTNAME',
    SET_USER_SECONDNAME: 'SET_USER_SECONDNAME',
    SET_USER_CAREEROBJECTIVE: 'SET_USER_CAREEROBJECTIVE',
    SET_USER_AGE: 'SET_USER_AGE',
    SET_USER_ABOUTME: 'SET_USER_ABOUTME',
    SET_USER_EMAIL: "SET_USER_EMAIL",
    SET_USER_VKONTAKTE: "SET_USER_VKONTAKTE",
    SET_USER_SKYPE: "SET_USER_SKYPE",
    SET_USER_PHONENUMBER: "SET_USER_PHONENUMBER",
    SET_USER_GITHUB: "SET_USER_GITHUB",
    SET_USER_FACEBOOK: "SET_USER_FACEBOOK",
}