 const actions = {
    SET_FIRSTNAME: 'SET_FIRSTNAME',
    SET_SECONDNAME: 'SET_SECONDNAME',
    SET_CAREEROBJECTIVE: 'SET_CAREEROBJECTIVE',
    SET_AGE: 'SET_AGE',
    SET_ABOUTME: 'SET_ABOUTME',
    SET_EMAIL: "SET_EMAIL",
    SET_VKONTAKTE: "SET_VKONTAKTE",
    SET_SKYPE: "SET_SKYPE",
    SET_PHONENUMBER: "SET_PHONENUMBER",
    SET_GITHUB: "SET_GITHUB",
    SET_FACEBOOK: "SET_FACEBOOK",
    SET_EDUCATION: "SET_EDUCATION",

    SET_FIRSTCOMPANY_NAME: 'SET_FIRSTCOMPANY_NAME',
    SET_FIRSTCOMPANY_POSITION: 'SET_FIRSTCOMPANY_POSITION',
    SET_FIRSTCOMPANY_DESCRIPTION: 'SET_FIRSTCOMPANY_DESCRIPTION',

    SET_SECONDCOMPANY_NAME: 'SET_SECONDCOMPANY_NAME',
    SET_SECONDCOMPANY_POSITION: 'SET_SECONDCOMPANY_POSITION',
    SET_SECONDCOMPANY_DESCRIPTION: 'SET_SECONDCOMPANY_DESCRIPTION',

    SET_FRONTEND: 'SET_FRONTEND',
    SET_BACKEND: 'SET_BACKEND',
    SET_DBS: 'SET_DBS',
    SET_OTHER: 'SET_OTHER',

    SET_FIRSTPROJECT_NAME: "SET_FIRSTPROJECT_NAME",
    SET_FIRSTPROJECT_LINK: "SET_FIRSTPROJECT_LINK",
    SET_FIRSTPROJECT_SUMMARY: "SET_FIRSTPROJECT_SUMMARY",
    SET_FIRSTPROJECT_WHATYOUDO: "SET_FIRSTPROJECT_WHATYOUDO",
    SET_FIRSTPROJECT_STACK: "SET_FIRSTPROJECT_STACK",

    SET_SECONDPROJECT_NAME: "SET_SECONDPROJECT_NAME",
    SET_SECONDPROJECT_LINK: "SET_SECONDPROJECT_LINK",
    SET_SECONDROJECT_SUMMARY: "SET_SECONDPROJECT_SUMMARY",
    SET_SECONDPROJECT_WHATYOUDO: "SET_SECONDPROJECT_WHATYOUDO",
    SET_SECONDPROJECT_STACK: "SET_SECONDPROJECT_STACK",

    SET_THIERDPROJECT_NAME: "SET_THIERDPROJECT_NAME",
    SET_THIERDPROJECT_LINK: "SET_THIERDPROJECT_LINK",
    SET_THIERDPROJECT_SUMMARY: "SET_THIERDPROJECT_SUMMARY",
    SET_THIERDPROJECT_WHATYOUDO: "SET_THIERDPROJECT_WHATYOUDO",
    SET_THIERDPROJECT_STACK: "SET_THIERDPROJECT_STACK",

    SET_FOURTHPROJECT_NAME: "SET_FOURTHPROJECT_NAME",
    SET_FOURTHPROJECT_LINK: "SET_FOURTHPROJECT_LINK",
    SET_FOURTHPROJECT_SUMMARY: "SET_FOURTHPROJECT_SUMMARY",
    SET_FOURTHPROJECT_WHATYOUDO: "SET_FOURTHPROJECT_WHATYOUDO",
    SET_FOURTHPROJECT_STACK: "SET_FOURTHPROJECT_STACK",
}

export default actions