 const actions = {
    SET_FIRSTNAME: 'SET_FIRSTNAME',
    SET_SECONDNAME: 'SET_SECONDNAME',
    SET_CAREEROBJECTIVE: 'SET_CAREEROBJECTIVE',
    SET_AGE: 'SET_AGE',
    SET_ABOUTME: 'SET_ABOUTME',
    SET_EMAIL: "SET_EMAIL",
    SET_VKONTAKTE: "SET_VKONTAKTE",
    SET_SKYPE: "SET_SKYPE",
    SET_PHONENUMBER: "SET_PHONENUMBER",
    SET_GITHUB: "SET_GITHUB",
    SET_FACEBOOK: "SET_FACEBOOK",

    SET_FIRSTCOMPANY_NAME: 'SET_FIRSTCOMPANY_NAME',
    SET_FIRSTCOMPANY_POSITION: 'SET_FIRSTCOMPANY_POSITION',
    SET_FIRSTCOMPANY_DESCRIPTION: 'SET_FIRSTCOMPANY_DESCRIPTION',

    SET_SECONDCOMPANY_NAME: 'SET_SECONDCOMPANY_NAME',
    SET_SECONDCOMPANY_POSITION: 'SET_SECONDCOMPANY_POSITION',
    SET_SECONDCOMPANY_DESCRIPTION: 'SET_SECONDCOMPANY_DESCRIPTION',

    SET_FRONTEND: 'SET_FRONTEND',
    SET_BACKEND: 'SET_BACKEND',
    SET_DBS: 'SET_DBS',
    SET_OTHER: 'SET_OTHER',
}

export default actions