const backendStack = [
    { title: 'Java' },
    { title: 'PHP' },
    { title: 'C#' },
    { title: 'VB' },
    { title: 'Ruby' },
    { title: 'Ruby on Rails' },
    { title: 'Python' },
    { title: 'JavaScript' },
    { title: 'Go' },
    { title: 'Kotlin' },
    { title: 'Swift' },
    { title: 'Dart' },
    { title: 'Rust' },
    { title: 'Scala' },
    { title: 'F#' },
    { title: 'Haskell' },
    { title: 'Bash' },
    { title: 'SQL' },
]