const frontendStack = [
  { title: "JavaScript" },
  { title: "HTML&CSS" },
  { title: "Webpack" },
  { title: "Node.js" },
  { title: "PHP" },
  { title: "Single Page Application" },
  { title: "TypeScript" },
  { title: "Ajax" },
  { title: "ECMAScript2015/2016" },
  { title: "Flux" },
  { title: "Reflux" },
  { title: "Redux" },
  { title: "Alt.js" },
  { title: "CORS" },
  { title: "XSS" },
  { title: "CSRF" },
  { title: "SQL" },
  { title: "XML" },
  { title: "REST API" },
  { title: "SEO" },
  { title: "UI/UX" },
  { title: "UNIX" },
  { title: "LINUX" },
  { title: "Java" },
  { title: "RoR" },
  { title: "Angular" },
  { title: "Angular 2" },
  { title: "Angular 2/4" },
  { title: "React" },
  { title: "Vue" },
  { title: "Bootstrap" },
  { title: "Material Design" },
  { title: "Material UI" },
  { title: "Grunt" },
  { title: "Gulp" },
  { title: "SUSY" },
  { title: "NPM" },
  { title: "LESS" },
  { title: "SASS" },
  { title: "SCSS" },
  { title: "jQuery" },
  { title: "Backbone.js" },
  { title: "Knockqut.js" },
  { title: "Underscore" },
  { title: "Lodash" },
  { title: "D3.js" },
  { title: "GSAP" },
  { title: "Superagent" },
  { title: "Git" },
  { title: "SVN" },
];

export default frontendStack;
